# Generated by Django 3.0.8 on 2020-12-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionlistings',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='auctionlistings',
            name='desc',
            field=models.CharField(default=256, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auctionlistings',
            name='pic',
            field=models.ImageField(default='default.jpg', upload_to='static/auctions'),
        ),
    ]
