# Generated by Django 3.0.8 on 2020-12-17 10:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20201216_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlistings',
            name='owner',
            field=models.CharField(default='admin', max_length=64),
        ),
        migrations.AddField(
            model_name='auctionlistings',
            name='time',
            field=models.CharField(default=datetime.datetime(2020, 12, 17, 10, 44, 44, 611376, tzinfo=utc), max_length=64),
        ),
    ]
