# Generated by Django 3.0.8 on 2020-12-19 17:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20201217_1044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='commenter',
            new_name='user',
        ),
        migrations.AddField(
            model_name='comments',
            name='listingid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comments',
            name='time',
            field=models.CharField(default=100, max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auctionlistings',
            name='time',
            field=models.CharField(default=datetime.datetime(2020, 12, 19, 17, 14, 18, 946077, tzinfo=utc), max_length=64),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.TextField(),
        ),
    ]
