# Generated by Django 3.0.8 on 2020-12-19 17:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20201219_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlistings',
            name='time',
            field=models.CharField(default=datetime.datetime(2020, 12, 19, 17, 14, 49, 45751, tzinfo=utc), max_length=64),
        ),
    ]
