# Generated by Django 3.0.8 on 2020-12-20 09:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20201219_1749'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bids',
            old_name='amount',
            new_name='bidamount',
        ),
        migrations.AddField(
            model_name='bids',
            name='bidowner',
            field=models.CharField(default=None, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bids',
            name='bidstart',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bids',
            name='listingid',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bids',
            name='numberofbids',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auctionlistings',
            name='time',
            field=models.CharField(default=datetime.datetime(2020, 12, 20, 9, 37, 6, 870229, tzinfo=utc), max_length=64),
        ),
        migrations.AlterField(
            model_name='comments',
            name='time',
            field=models.CharField(default=datetime.datetime(2020, 12, 20, 9, 37, 6, 871512, tzinfo=utc), max_length=64),
        ),
    ]
