# Generated by Django 3.0.8 on 2020-12-20 10:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auto_20201220_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bids',
            name='numberofbids',
        ),
        migrations.AlterField(
            model_name='auctionlistings',
            name='time',
            field=models.CharField(default=datetime.datetime(2020, 12, 20, 10, 35, 53, 409843, tzinfo=utc), max_length=64),
        ),
        migrations.AlterField(
            model_name='comments',
            name='time',
            field=models.CharField(default=datetime.datetime(2020, 12, 20, 10, 35, 53, 411041, tzinfo=utc), max_length=64),
        ),
    ]
