# Generated by Django 3.0.8 on 2020-12-22 18:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_auto_20201222_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alllisting',
            name='link',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='auctionlistings',
            name='time',
            field=models.CharField(default=datetime.datetime(2020, 12, 22, 18, 11, 48, 378358, tzinfo=utc), max_length=256),
        ),
        migrations.AlterField(
            model_name='comments',
            name='time',
            field=models.CharField(default=datetime.datetime(2020, 12, 22, 18, 11, 48, 379356, tzinfo=utc), max_length=64),
        ),
    ]
