# Generated by Django 3.0.8 on 2020-12-22 18:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_auto_20201222_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlistings',
            name='link',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='auctionlistings',
            name='time',
            field=models.CharField(default=datetime.datetime(2020, 12, 22, 18, 12, 28, 461051, tzinfo=utc), max_length=64),
        ),
        migrations.AlterField(
            model_name='comments',
            name='time',
            field=models.CharField(default=datetime.datetime(2020, 12, 22, 18, 12, 28, 462112, tzinfo=utc), max_length=64),
        ),
    ]
